### ISSUE TITLE
instagram doesnt work

### ISSUE THREAD

**Issue by 89z** [xIceArcher/go-leah#1]
Using this test:

~~~go
package instagram

import (
   "github.com/xIceArcher/go-leah/config"
   "testing"
)

func TestInsta(t *testing.T) {
   a, err := NewAPI(&config.InstaConfig{"http://instagram.com/p/%s"})
   if err != nil {
      t.Fatal(err)
   }
   if _, err := a.GetPost("CT-cnxGhvvO"); err != nil {
      t.Fatal(err)
   }
}
~~~

I get this result:

~~~
http error 429
~~~

**Comment by xIceArcher** [comment]
This project is primarily a Discord bot, if you're looking just for an Instagram API wrapper, you might want to look elsewhere.

That being said, the Instagram feature in this project assumes the use of some service to extract the relevant post information from Instagram. You can find an example of this at https://github.com/xIceArcher/instaproxy

Also, a quick Google search will tell you that HTTP error 429 corresponds to this https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 , which has nothing at all to do with the functionality of the code in this project.

**Comment by 89z** [comment]
> Also, a quick Google search will tell you that HTTP error 429 corresponds to this https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 , which has nothing at all to do with the functionality of the code in this project.

Its frustrating that I keep having to repeat this in different repositories, but you are mistaken. After my own checking, the issue is because this package (and others) are using the default User-Agent, instead of a browser User-Agent such as `Mozilla`. I know this is true, as the exact URL above works in my browser, and even works with this package, if you make that change.

It would be good if you actually check what you are saying, instead of quoting random stuff that doesnt relate to or solve the problem.

**Comment by xIceArcher** [comment]
> That being said, the Instagram feature in this project assumes the use of some service to extract the relevant post information from Instagram. You can find an example of this at https://github.com/xIceArcher/instaproxy

To reiterate what I said, the code in this project would not work independently even if you added the correct User-Agent, because this project is not meant to query Instagram directly. It needs to go through a service that extracts the relevant JSON containing the post information from Instagram.
